# Generated by Django 3.2.23 on 2024-01-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='source_website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
