# Generated by Django 3.2.23 on 2024-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0002_auto_20240115_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
