# Generated by Django 3.2.23 on 2024-01-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0003_auto_20240115_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
