# Generated by Django 3.2.23 on 2024-01-21 18:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
