# Generated by Django 3.2.23 on 2024-01-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0005_auto_20240121_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summery',
            field=models.TextField(null=True),
        ),
    ]
