# Generated by Django 3.2.23 on 2024-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0007_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
