# Generated by Django 3.2.23 on 2024-02-12 10:34

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0009_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=70, verbose_name='پرونده')),
                ('publisher', models.CharField(max_length=70, verbose_name='ناشر')),
                ('author', models.CharField(max_length=70, verbose_name='نویسنده')),
                ('ro_titer', models.CharField(blank=True, max_length=70, null=True, verbose_name='رو تیتر')),
                ('h1', models.CharField(blank=True, max_length=70, null=True, verbose_name='تگ h1')),
                ('slog', models.CharField(blank=True, max_length=25, null=True, verbose_name='نامک')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='عنوان')),
                ('snippet', models.TextField(verbose_name='چکیده')),
                ('meta_kword', models.CharField(max_length=70, verbose_name='کلمه متا')),
                ('meta_description', models.CharField(blank=True, max_length=127, null=True, verbose_name='توضیحات متا')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.CharField(blank=True, max_length=70, null=True, verbose_name='تصویر')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='لینک تصویر')),
                ('video', models.CharField(blank=True, max_length=70, null=True, verbose_name='ویدئو')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدئو')),
                ('url', models.CharField(blank=True, max_length=70, null=True, verbose_name='لینک')),
                ('embed_code', models.TextField(blank=True, null=True, verbose_name='کد امبد')),
                ('media_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات رسانه استفاده شده')),
                ('type_of_news', models.CharField(blank=True, max_length=70, null=True, verbose_name='نوع خبر')),
                ('source_website', models.CharField(blank=True, max_length=70, null=True, verbose_name='منبع خبر')),
                ('tags', models.CharField(max_length=70, verbose_name=' تگ')),
                ('counted_views', models.IntegerField(default=0, null=True, verbose_name='تعداد بازدید')),
                ('status', models.BooleanField(default=False, verbose_name='رسیدن زمان انتشار')),
                ('confirm_to_post', models.BooleanField(default=False, verbose_name='پست تایید شده؟')),
                ('supervisor_to_confirm', models.CharField(max_length=70, null=True, verbose_name='سرپرست تایید کننده پست')),
                ('trash', models.BooleanField(default=False, verbose_name='زباله دان')),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی')),
                ('published_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ انتشار')),
            ],
        ),
    ]
