# Generated by Django 3.2.23 on 2024-02-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0010_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='لینک تصویر'),
        ),
    ]
