# Generated by Django 3.2.23 on 2024-02-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0012_alter_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
