# Generated by Django 3.2.23 on 2024-02-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0014_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='folder_name',
            field=models.CharField(max_length=250, verbose_name='پرونده'),
        ),
    ]
