# Generated by Django 3.2.23 on 2024-02-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0016_auto_20240217_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_kword',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='کلمه متا'),
        ),
    ]
