# Generated by Django 3.2.23 on 2024-02-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsel', '0017_alter_post_meta_kword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='رسیدن زمان انتشار'),
        ),
    ]
